### PR TITLE
Dockerize the Project Service!

### PR DESCRIPTION
**Pull request by kurtlewis**
This is a work in progress PR for adding the Dockerfile to the project service. I'm going to use it as a place for a to do list, and a place to track conversation over needs from other people.

I'll add a review request when I"m done.

To do:
- [x] Need to manage setting env variables at runtime (probably by making a script)
- [x] Need a production runner from @zacharysang, i.e. `nodejs app.js` or `npm start`
- [ ] make the image smaller (low priority)

### CODE REVIEW

**Comment by kurtlewis** [comment]
Looks like the correct methodology for managing variables will be via setting environment variables when I run the container. 

See the newly committed README.md for instructions on running with the correct commands

**Comment by zacharysang** [comment]
@kurtlewis  For your production start command, what do you need that differs from the dev environment? We already have port and url passable through env vars, but not sure if you need anything else on your end.

Right now we do a check for the `FLOCK_DEV` env var to enable dev-specific stuff (ngrok temporary url, locally hosting JS and HTML resources, etc.).

If what we have right now is good enough for you, we may just want to modify package.json so that `npm run dev` -> `npm start`

**Comment by kurtlewis** [comment]
That's up to you! I just need to know what command should be run in a live
scenario. `npm start` is fine with me.

Will we need to do localtunnel or gronk for our production environment? I
noticed that's part of `npm dev` which is really what prompted me to ask

**Comment by zacharysang** [comment]
So yeah, in that case `npm run dev` is probably good to run. You should be fine to change it or copy it to the start command if you want (or I can do it on my next commit on a different task).

We won't be running ngrok in production, but when you merge with master, that should go away anyways ([this is the latest version of that command](https://github.com/zacharysang/flock/blob/master/project_service/package.json#L7))

**Comment by kurtlewis** [comment]
Aha! Very good, hadnt realized you'd changed it. I'll merge master in and
verify things!

Thanks!

**Comment by kurtlewis** [comment]
@zacharysang Looks like you `require('ngrok')' in `app.js` regardless of environment, and have it marked as a dev dependency.
```
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'ngrok'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/opt/rtc-server/app.js:41:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

**Comment by zacharysang** [comment]
Gotcha, yeah. I should be able to fix that sometime tomorrow

**Pull request merged**
